# Generated by Django 5.0.3 on 2024-04-05 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='point',
        ),
    ]
